const results = {
  recipes: [
    {
      recipe_id: 67704183,
      title: "Italian Riso Venere and Burrata Salad",
      attributes: ["Easy", "Salad", "30m", "4 Servings"],
      ingredients: ["Riso venere", "Ravanelli", "Burrata", "Zucchine"],
      ing_quantities: [
        "250g Riso venere",
        "200g Ravanelli, thinly sliced",
        "200g Burrata, torn into pieces",
        "300g Zucchine, sliced into half moons",
      ],
      preparation: [
        [
          "Step 1: Cook the Riso Venere",
          "Rinse the Riso venere under cold water.",
          "Boil in salted water for 30 minutes or until al dente.",
          "Drain and let cool.",
        ],
        [
          "Step 2: Prepare the Vegetables",
          "Slice the ravanelli thinly.",
          "Slice the zucchine into half-moon shapes.",
        ],
        [
          "Step 3: Assemble the Salad",
          "Combine the cooled Riso venere, ravanelli, and zucchine in a large bowl.",
          "Gently mix in the burrata.",
          "Season with salt and pepper to taste.",
        ],
      ],
      is_favorited: false,
      is_gluten_free: true,
      is_vegetarian: true,
      is_vegan: false,
      cuisine_ethnicity: "Italian",
      caloric_apport: 350,
      preparation_time: 30,
      difficulty: "easy",
    },
    {
      recipe_id: 38204579,
      title: "Middle Eastern Inspired Zucchini and Burrata Rice Bowl",
      attributes: ["Medium", "Main Course", "40m", "4 Servings"],
      ingredients: ["Riso venere", "Ravanelli", "Burrata", "Zucchine"],
      ing_quantities: [
        "250g Riso venere",
        "100g Ravanelli, thinly sliced",
        "200g Burrata, sliced",
        "400g Zucchine, diced",
      ],
      preparation: [
        [
          "Step 1: Cook the Rice",
          "Rinse the Riso venere and cook in boiling salted water for 30 minutes.",
          "Drain and keep warm.",
        ],
        [
          "Step 2: Sauté the Zucchine",
          "In a pan, heat some olive oil over medium heat.",
          "Add the diced zucchine and sauté until tender and golden.",
          "Season with salt, pepper, and a touch of cumin.",
        ],
        [
          "Step 3: Prepare the Salad",
          "Mix the sliced ravanelli with a tablespoon of lemon juice and a pinch of salt.",
        ],
      ],
      is_favorited: false,
      is_gluten_free: true,
      is_vegetarian: true,
      is_vegan: false,
      cuisine_ethnicity: "Middle Eastern",
      caloric_apport: 400,
      preparation_time: 40,
      difficulty: "medium",
    },
    {
      recipe_id: 19453726,
      title: "Greek-Inspired Riso Venere Bowl with Radishes and Burrata",
      attributes: ["Easy", "Main Dish", "45m", "4 Servings"],
      ingredients: ["Riso venere", "Ravanelli", "Burrata", "Zucchine"],
      ing_quantities: [
        "250g Riso venere",
        "150g Ravanelli, sliced",
        "200g Burrata, roughly torn",
        "300g Zucchine, grilled",
      ],
      preparation: [
        [
          "Step 1: Cook Riso Venere",
          "Rinse the Riso venere.",
          "Boil in salted water for about 35 minutes until tender.",
          "Drain and set aside.",
        ],
        [
          "Step 2: Prepare Zucchine",
          "Slice zucchine and grill them until tender and charred.",
          "Season with salt and olive oil.",
        ],
        [
          "Step 3: Assemble the Bowl",
          "Combine cooled Riso venere with grilled zucchine and ravanelli.",
          "Top with burrata and a drizzle of olive oil.",
          "Serve with optional herbs like fresh basil or mint.",
        ],
      ],
      is_favorited: false,
      is_gluten_free: true,
      is_vegetarian: true,
      is_vegan: false,
      cuisine_ethnicity: "Greek",
      caloric_apport: 450,
      preparation_time: 45,
      difficulty: "easy",
    },
  ],
};
